---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: admin
      port: 8877
      targetPort: 8877
  selector:
    service: ambassador